- ec2_scaling_policy:
    state: present
    region: "{{ region }}"
    adjustment_type: "ChangeInCapacity"
    asg_name: "{{ asg_name }}"
    scaling_adjustment: "{{ item.scaling_adjustment }}"
    min_adjustment_step: 1
    cooldown: "{{ item.cooldown }}"
    name: "{{item.name }}"
  register: "sp_result"
  with_items: "{{scaling_policies}}"

- debug: msg="{{sp_result}}"

- debug:
    msg="{{item[1]['name']}} == {{item[0]['scaling_policy_name']}}"
  with_nested:
    - "{{alarm_metrics}}"
    - "{{sp_result.results}}"
- ec2_metric_alarm:
    state: present
    region: "{{ region }}"
    name: "{{ item[0].name }}"
    metric: "{{ item[0].metric }}"
    namespace: "AWS/EC2"
    statistic: "{{ item[0].statistics }}"
    comparison: "{{ item[0].comparison }}"
    threshold: "{{ item[0].threshold }}"
    period: "{{ item[0].period }}"
    evaluation_periods: "{{ item[0].evaluation_periods }}"
    unit: "{{ item[0].unit }}"
    description: "{{ item[0].description }}"
    dimensions: "{{ item[0].dimensions }}"
    alarm_actions: "{{ item[1]['arn'] }}"
  when: "'{{item[1].name}}' == '{{item[0].scaling_policy_name}}'"
  with_nested:
    - "{{alarm_metrics}}"
    - "{{sp_result.results}}"
